# Use postgres/example user/password credentials
version: '3.9'

services:

  db:
    image: postgres:10
    container_name: posrgress_10_exemplo
    restart: always
    shm_size: 128mb
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
